name: Auto Commit Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'   # Every 2 hours at minute 0
  workflow_dispatch:         # Optional: allows manual runs

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update daily log file
        run: |
          echo "$(date -u +"%Y-%m-%d %H:%M:%S UTC") - Auto-update from GitHub Actions" >> daily-log.txt

      - name: Set up Git user (use your own GitHub identity)
        run: |
          git config user.name "BiswojitOps"  # Replace with your GitHub username
          git config user.email "biswojit987@gmail.com"  # Must be your verified GitHub email

      - name: Commit and push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add daily-log.txt
          git commit -m "chore: auto update at $(date -u)" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git push

      - name: Debug recent commits
        run: git log -5 --oneline
