name: Auto Commit with Random Behavior

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add random delay
        run: |
          delay=$((RANDOM % 300))
          echo "Sleeping for $delay seconds..."
          sleep $delay

      - name: Update daily log file
        run: |
          today=$(date -u +"%Y-%m-%d")
          mkdir -p logs
          echo "$(date -u +"%Y-%m-%d %H:%M:%S UTC") - Auto-update" >> logs/log-$today.txt

      - name: Set up Git identity
        run: |
          git config user.name "BiswojitOps"
          git config user.email "biswojit987@gmail.com"

      - name: Commit and push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add .
          messages=("update logs" "auto sync" "routine data update" "keep-alive commit" "timestamp update" "log patch")
          random_message=${messages[$RANDOM % ${#messages[@]}]}
          git commit -m "$random_message - $(date -u)" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git push
