name: 3 Daily Commits

on:
  schedule:
    - cron: '0 6 * * *'   # 06:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 18 * * *'  # 18:00 UTC
  workflow_dispatch:      # Allows manual runs

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update daily log file
        run: |
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          echo "$timestamp - GitHub Actions auto-commit" >> daily-log.txt

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add daily-log.txt
          git commit -m "chore: auto update at $timestamp"
          git push
